language: go
go:
  - 1.11
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS GOW;'
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go build .
script:
  - go test -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci