language: go
go:
  - master

os:
  - linux

dist: trusty
sudo: false 

install: true
services:
  - mysql
before_install:
  - mysql < $HOME/gopath/src/github.com/SCK-SEAL-TEAM-One/GOW/src/gow-backend/sql/gow.sql
install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g newman
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script: cd $HOME/gopath/src/github.com/SCK-SEAL-TEAM-One/GOW/src/gow-backend/gow
script:
  - env GO111MODULE=on go build .
  - env GO111MODULE=on go test -covermode=count -coverprofile=coverage.out ./...
  - env GO111MODULE=on $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - ./gow &
  - newman run $HOME/gopath/src/github.com/SCK-SEAL-TEAM-One/GOW/src/gow-backend/atdd/api/gow-backend.json