language: go
go:
  - master

os:
  - linux

dist: trusty
sudo: false 

install: true
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS GOW;'
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script: cd $HOME/gopath/src/github.com/SCK-SEAL-TEAM-One/GOW/src/gow-backend/gow
script:
  - ls $HOME/gopath/bin/
  - env GO111MODULE=on go build 
  - env GO111MODULE=on go test -covermode=count -coverprofile=coverage.out
  - env GO111MODULE=on go $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci