CREATE TABLE IF NOT EXISTS customer (
customer_id INT(3) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
customer_name VARCHAR(512) NOT NULL,
customer_branch VARCHAR(256) NOT NULL,
customer_address VARCHAR(256),
customer_taxid VARCHAR(13) UNIQUE,
created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_time DATETIME ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS company (
company_id INT(3) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
company_name VARCHAR(512) NOT NULL,
company_branch VARCHAR(256) NOT NULL,
company_address VARCHAR(256),
company_taxid VARCHAR(13) UNIQUE,
company_phonenumber VARCHAR(13),
created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_time DATETIME ON UPDATE CURRENT_TIMESTAMP
)