version: '3'
services:
  gow-frontend:
    build: ./gow-frontend
    links:
    - gow-backend
    ports:
    - "80:80"
    volumes:
    - ./gow-frontend/ui.conf:/etc/nginx/conf.d/default.conf
    - ./gow-frontend/public/:/usr/share/nginx/html:ro
  # gow-backend:
  #   image: datecal:latest
  #   ports:
  #   - "3001:3001"
  backend:
    build: ./gow-backend
    links:
    - mysql
    ports:
    - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./gow-backend/sql/gow.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sckshuhari